<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>3DPipes</AssemblyName>
    <RootNamespace>ThreeDPipesScreensaver</RootNamespace>
    <ApplicationIcon>assets\3dpipes.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\ThreeDPipes.cs" />
    <Compile Include="src\PipeWorld.cs" />
    <Compile Include="src\OpenGlRenderer.cs" />
  </ItemGroup>
</Project>
